### ISSUE TITLE
Libo3d3xx and Windows

### ISSUE THREAD

**Issue by pfrydlewicz** [lovepark/libo3d3xx#111]
Hello

As far as I've seen the cmake files the libo3d3xx is for linux only, right?

The lib seems to be well implemented to work with the cameras.

What would be necessary to port it to windows? (Ideally visual studio).
Thank you for response.

Paul

**Comment by pfrydlewicz** [comment]
Sorry, just realized that there is already an open thread on that topic...

**Comment by graugans** [comment]
This is a duplicate of Issue #104
