### ISSUE TITLE
BUILD_SHARED_LIBS Cmake option is not ignored

### ISSUE THREAD

**Issue by semsitivity** [lovepark/libo3d3xx#12]
There are currently no way to build lib3d3xx as static library, it could be usefull to  take care about this parameter in order to do it.

**Comment by tpanzarella** [comment]
This is implemented in 0.2.0. While not currently released, I have pushed my dev branch `dev-0.2.0` out to github, so, if you want to play with this now, it is available.

I should note that the static library building only builds our code statically. However, downstream dependencies may not have static libraries available and hence will be linked dynamically. In the future I may add a "strict static" option or something like that where the build will error out if everything is not available statically, but for now, hopefully this gives you what you are looking for.
