### ISSUE TITLE
More CMake option to disable binaries compilation one by one

### ISSUE THREAD

**Issue by semsitivity** [lovepark/libo3d3xx#13]
Adding some boolean options like
BUILD_CONFIG
BUILD_DUMP
BUILD_HZ
BUILD_IFM_IMPORT
BUILD_IFM_EXPORT
BUILD_IMAGER_TYPES
...
and specially
BUILD_VIEWER

can be very usefull, specifically when you need to avoid building gtest, or pcl visualization library.

**Comment by tpanzarella** [comment]
This is implemented in 0.2.0. While not currently released, I have pushed my dev branch `dev-0.2.0` to github, so, if you want to play with this now, it is available.
