### ISSUE TITLE
XYZ axis

### ISSUE THREAD

**Issue by semsitivity** [lovepark/libo3d3xx#16]
This is just a question about [this piece](https://github.com/lovepark/libo3d3xx/blob/master/src/libo3d3xx/image.cpp#L317) of code in image.cpp.
@tpanzarella , you comment that you rotate the point cloud into right handed axis system.
I'm a bit confused here, and would like to get a confirmation about the original axis orientation from @graugans. Are the camera axis system is Z for depth, Y for "hight" and X for horizontal axis?

To give you more context, I compute the floor vector from the point cloud returned by libo3d3xx, which has been rotated 
libo3d3xx.x --> ifm.z
libo3d3xx.y --> -ifm.x
libo3d3xx.z --> -ifm.y

After computing the rotation, I set ExtrinsecRot and ExtrinstecTrans in order to get a floor oriented point cloud out of the camera, but I consider only a rotation arround for the camera pitch according [this picture](http://www.photoactivity.com/Pagine/Articoli/017%20Stitch%20approfondimento/Yaw%20Pitch%20Roll.jpg) , and a translation to set floor at 0 on "vertical axis" (which was Y in my algorithm).
So if you can give me some clue about original axis system, I'll understand more the libo3d3xx and probably won't be lost anymore ;)

**Comment by tpanzarella** [comment]
To provide some context, the point cloud is constructed based on [ROS conventions](http://wiki.ros.org/geometry/CoordinateFrameConventions) for coord frames. There is definitely a bias toward using the library underneath [o3d3xx-ros](https://github.com/lovepark/o3d3xx-ros) as that is/was my original use case when initially writing the library. 

@semsitivity makes good points about it being a bit awkward when storing and applying an extrinsic calibration in the sensor's firmware. I think I mentioned it in a comment in issue #14 and I think this further supports my desire to have a way to separate storing and applying the extrinsics in the firmware. I.e., I may want to store my extrinsics on the camera based on the coord frame of the PCL point cloud at which point I can perform the transform in my application code. However, someone who is not using `libo3d3xx` may want the extrinsics applied by the sensor as they are using the default coord frame conventions. To do this, having a boolean flag at the application level that indicates to the firmware whether or not to apply the stored extrinsics would be great.
