### ISSUE TITLE
stripped down library

### ISSUE THREAD

**Issue by Postea-CS** [lovepark/libo3d3xx#40]
I notice that the dependencies include PCL and Opencv. the chained dependencies makes the required installation pretty big. I only needs the raw images from the sensors and not the post processing part. Any recommendations on possibly getting a strip down version?
thanks

**Comment by tpanzarella** [comment]
The next release of the software will include a significant modularity refactoring.  In short, we will be breaking the library apart into roughly the following components: `common`, `config`, `framegrabber`, and `image`. The last of which will carry the OpenCV and PCL dependency. The `framegrabber` will allow for just getting a simple byte buffer from the camera from which you can construct into whatever image data structure is most convenient for your environment. Realistically it should be available mid-to-late March.

Tagging @graugans as this will be of interest to him as well.
