### ISSUE TITLE
New procedure for packaging debs in v0.4.0

### ISSUE THREAD

**Issue by bigcmos** [lovepark/libo3d3xx#48]
I just tried migrating to v0.4.0 and I noticed that the high level `make package` disappeared.  Do you plan to add new make package script that will build all of the modules?

**Comment by tpanzarella** [comment]
At the individual module level there are still make package targets. Also,
at the top level the debs are still created. They should be in your build
directory. Just grep for them.

--
Tom Panzarella
(sent from my phone)
