### ISSUE TITLE
make check (AppImagerTest.Get*Parameters) fails on O3D303 Camera

### ISSUE THREAD

**Issue by NamanCMU** [lovepark/libo3d3xx#51]
Hi all,

I am trying to use libo3d3xx with our IFM O3D303 Camera and eventually I want to use o3d3xx-ros to extract the Point Cloud from the camera and use it for navigation of our Robot. I am able to ping the camera but when I run **make** inside the build directory, I get the following output with 2 Failed tests (AppImagerTest.GetAppParameters and AppImagerTest.GetImagerParameters Tests failed) : 

namanpc@namanpc-All-Series:~/libo3d3xx/build$ make
Scanning dependencies of target O3D3XX_CAMERA
[  3%] Creating directories for 'O3D3XX_CAMERA'
[  6%] No download step for 'O3D3XX_CAMERA'
[ 10%] No patch step for 'O3D3XX_CAMERA'
[ 13%] No update step for 'O3D3XX_CAMERA'
[ 16%] Performing configure step for 'O3D3XX_CAMERA'
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   system
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/namanpc/libo3d3xx/build/O3D3XX_CAMERA-prefix/src/O3D3XX_CAMERA-build
[ 20%] Performing build step for 'O3D3XX_CAMERA'
Scanning dependencies of target o3d3xx_camera
[  3%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/net_config.cpp.o
[  6%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/device_config.cpp.o
[ 10%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/spatial_filter_config.cpp.o
[ 13%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/err.cpp.o
[ 16%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/camera.cpp.o
[ 20%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/app_config.cpp.o
[ 23%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/cmdline_opts.cpp.o
[ 26%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/util.cpp.o
[ 30%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/version.cpp.o
[ 33%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/temporal_filter_config.cpp.o
[ 36%] Building CXX object src/libo3d3xx_camera/CMakeFiles/o3d3xx_camera.dir/imager_config.cpp.o
[ 36%] Built target o3d3xx_camera
Scanning dependencies of target o3d3xx_camera_shared
Linking CXX shared library libo3d3xx_camera.so
[ 36%] Built target o3d3xx_camera_shared
Scanning dependencies of target o3d3xx_camera_static
Linking CXX static library libo3d3xx_camera_static.a
[ 36%] Built target o3d3xx_camera_static
Scanning dependencies of target o3d3xx-config
[ 40%] Building CXX object src/bin/CMakeFiles/o3d3xx-config.dir/o3d3xx-config.cpp.o
Linking CXX executable o3d3xx-config
[ 40%] Built target o3d3xx-config
Scanning dependencies of target o3d3xx-dump
[ 43%] Building CXX object src/bin/CMakeFiles/o3d3xx-dump.dir/o3d3xx-dump.cpp.o
Linking CXX executable o3d3xx-dump
[ 43%] Built target o3d3xx-dump
Scanning dependencies of target o3d3xx-ifm-export
[ 46%] Building CXX object src/bin/CMakeFiles/o3d3xx-ifm-export.dir/o3d3xx-ifm-export.cpp.o
Linking CXX executable o3d3xx-ifm-export
[ 46%] Built target o3d3xx-ifm-export
Scanning dependencies of target o3d3xx-ifm-import
[ 50%] Building CXX object src/bin/CMakeFiles/o3d3xx-ifm-import.dir/o3d3xx-ifm-import.cpp.o
Linking CXX executable o3d3xx-ifm-import
[ 50%] Built target o3d3xx-ifm-import
Scanning dependencies of target o3d3xx-imager-types
[ 53%] Building CXX object src/bin/CMakeFiles/o3d3xx-imager-types.dir/o3d3xx-imager-types.cpp.o
Linking CXX executable o3d3xx-imager-types
[ 53%] Built target o3d3xx-imager-types
Scanning dependencies of target o3d3xx-ls
[ 56%] Building CXX object src/bin/CMakeFiles/o3d3xx-ls.dir/o3d3xx-ls.cpp.o
Linking CXX executable o3d3xx-ls
[ 56%] Built target o3d3xx-ls
Scanning dependencies of target o3d3xx-reboot
[ 60%] Building CXX object src/bin/CMakeFiles/o3d3xx-reboot.dir/o3d3xx-reboot.cpp.o
Linking CXX executable o3d3xx-reboot
[ 60%] Built target o3d3xx-reboot
Scanning dependencies of target o3d3xx-reset
[ 63%] Building CXX object src/bin/CMakeFiles/o3d3xx-reset.dir/o3d3xx-reset.cpp.o
Linking CXX executable o3d3xx-reset
[ 63%] Built target o3d3xx-reset
Scanning dependencies of target o3d3xx-rm
[ 66%] Building CXX object src/bin/CMakeFiles/o3d3xx-rm.dir/o3d3xx-rm.cpp.o
Linking CXX executable o3d3xx-rm
[ 66%] Built target o3d3xx-rm
Scanning dependencies of target o3d3xx-version
[ 70%] Building CXX object src/bin/CMakeFiles/o3d3xx-version.dir/o3d3xx-version.cpp.o
Linking CXX executable o3d3xx-version
[ 70%] Built target o3d3xx-version
Scanning dependencies of target gtest
[ 73%] Building CXX object test/gtest_bin/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX shared library libgtest.so
[ 73%] Built target gtest
Scanning dependencies of target gtest_main
[ 76%] Building CXX object test/gtest_bin/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX shared library libgtest_main.so
[ 76%] Built target gtest_main
Scanning dependencies of target o3d3xx-camera-tests
[ 80%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-camera-tests.cpp.o
[ 83%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-camera-testrunner.cpp.o
[ 86%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-import-export-tests.cpp.o
[ 90%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-app-imager-tests.cpp.o
[ 93%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-temporal-filter-tests.cpp.o
[ 96%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-spatial-filter-tests.cpp.o
[100%] Building CXX object test/CMakeFiles/o3d3xx-camera-tests.dir/o3d3xx-basic-tests.cpp.o
Linking CXX executable o3d3xx-camera-tests
[100%] Built target o3d3xx-camera-tests
[ 23%] Performing test step for 'O3D3XX_CAMERA'
[  5%] Built target gtest
[ 60%] Built target o3d3xx_camera
[ 60%] Built target o3d3xx_camera_shared
[ 65%] Built target gtest_main
[100%] Built target o3d3xx-camera-tests
Scanning dependencies of target check
[==========] Running 43 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 17 tests from Camera_Tests
[ RUN      ] Camera_Tests.Ctor
[       OK ] Camera_Tests.Ctor (0 ms)
[ RUN      ] Camera_Tests.GetXMLRPCURLPrefix
[       OK ] Camera_Tests.GetXMLRPCURLPrefix (1 ms)
[ RUN      ] Camera_Tests.GetAllParameters
[       OK ] Camera_Tests.GetAllParameters (595 ms)
[ RUN      ] Camera_Tests.GetParameter
[       OK ] Camera_Tests.GetParameter (1105 ms)
[ RUN      ] Camera_Tests.GetSWVersion
[       OK ] Camera_Tests.GetSWVersion (17 ms)
[ RUN      ] Camera_Tests.GetApplicationList
[       OK ] Camera_Tests.GetApplicationList (13 ms)
[ RUN      ] Camera_Tests.RequestSession
[       OK ] Camera_Tests.RequestSession (38 ms)
[ RUN      ] Camera_Tests.CancelSession
[       OK ] Camera_Tests.CancelSession (41 ms)
[ RUN      ] Camera_Tests.Heartbeat
[       OK ] Camera_Tests.Heartbeat (56 ms)
[ RUN      ] Camera_Tests.SetOperatingMode
[       OK ] Camera_Tests.SetOperatingMode (357 ms)
[ RUN      ] Camera_Tests.GetDeviceConfig
[       OK ] Camera_Tests.GetDeviceConfig (873 ms)
[ RUN      ] Camera_Tests.ActivateDisablePassword
[       OK ] Camera_Tests.ActivateDisablePassword (446 ms)
[ RUN      ] Camera_Tests.SetDeviceConfig
[       OK ] Camera_Tests.SetDeviceConfig (2284 ms)
[ RUN      ] Camera_Tests.DeviceConfig_JSON
[       OK ] Camera_Tests.DeviceConfig_JSON (270 ms)
[ RUN      ] Camera_Tests.GetNetParameters
[       OK ] Camera_Tests.GetNetParameters (356 ms)
[ RUN      ] Camera_Tests.NetConfig
[       OK ] Camera_Tests.NetConfig (417 ms)
[ RUN      ] Camera_Tests.NetConfig_JSON
[       OK ] Camera_Tests.NetConfig_JSON (410 ms)
[----------] 17 tests from Camera_Tests (7280 ms total)

[----------] 1 test from ImportExport_Tests
[ RUN      ] ImportExport_Tests.ImportExportApp
[       OK ] ImportExport_Tests.ImportExportApp (964 ms)
[----------] 1 test from ImportExport_Tests (964 ms total)

[----------] 15 tests from AppImagerTest
[ RUN      ] AppImagerTest.CopyDeleteApplication
[       OK ] AppImagerTest.CopyDeleteApplication (1123 ms)
[ RUN      ] AppImagerTest.CreateApplication
[       OK ] AppImagerTest.CreateApplication (713 ms)
[ RUN      ] AppImagerTest.ChangeAppNameAndDescription
[       OK ] AppImagerTest.ChangeAppNameAndDescription (1016 ms)
[ RUN      ] AppImagerTest.EditApplication
[       OK ] AppImagerTest.EditApplication (1132 ms)
[ RUN      ] AppImagerTest.GetAppParameters
/home/namanpc/libo3d3xx/modules/camera/test/o3d3xx-app-imager-tests.cpp:131: Failure
Value of: 8
Expected: params.size()
Which is: 9
[  FAILED  ] AppImagerTest.GetAppParameters (1466 ms)
[ RUN      ] AppImagerTest.AppConfig
[       OK ] AppImagerTest.AppConfig (1866 ms)
[ RUN      ] AppImagerTest.AppConfig_JSON
[       OK ] AppImagerTest.AppConfig_JSON (1723 ms)
[ RUN      ] AppImagerTest.GetAvailableImagerTypes
[       OK ] AppImagerTest.GetAvailableImagerTypes (1489 ms)
[ RUN      ] AppImagerTest.ChangeImagerType
[       OK ] AppImagerTest.ChangeImagerType (2840 ms)
[ RUN      ] AppImagerTest.GetImagerParameters
/home/namanpc/libo3d3xx/modules/camera/test/o3d3xx-app-imager-tests.cpp:279: Failure
Expected: params.at("MaxAllowedLEDFrameRate") doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AppImagerTest.GetImagerParameters (1761 ms)
[ RUN      ] AppImagerTest.GetImagerParameterLimits
[       OK ] AppImagerTest.GetImagerParameterLimits (2879 ms)
[ RUN      ] AppImagerTest.ImagerConfig
[       OK ] AppImagerTest.ImagerConfig (4629 ms)
[ RUN      ] AppImagerTest.ImagerConfigValueOutOfRange
[       OK ] AppImagerTest.ImagerConfigValueOutOfRange (2951 ms)
[ RUN      ] AppImagerTest.ImagerConfig_JSON
[       OK ] AppImagerTest.ImagerConfig_JSON (1488 ms)
[ RUN      ] AppImagerTest.Exposure
[       OK ] AppImagerTest.Exposure (3720 ms)
[----------] 15 tests from AppImagerTest (30800 ms total)

[----------] 4 tests from TemporalFilterTest
[ RUN      ] TemporalFilterTest.TemporalFilterConfig_General
[       OK ] TemporalFilterTest.TemporalFilterConfig_General (1061 ms)
[ RUN      ] TemporalFilterTest.GetTemporalFilterParameters
[       OK ] TemporalFilterTest.GetTemporalFilterParameters (1975 ms)
[ RUN      ] TemporalFilterTest.GetTemporalFilterParameterLimits
[       OK ] TemporalFilterTest.GetTemporalFilterParameterLimits (2019 ms)
[ RUN      ] TemporalFilterTest.TemporalFilterConfig_JSON
[       OK ] TemporalFilterTest.TemporalFilterConfig_JSON (2030 ms)
[----------] 4 tests from TemporalFilterTest (7085 ms total)

[----------] 4 tests from SpatialFilterTest
[ RUN      ] SpatialFilterTest.SpatialFilterConfig_General
[       OK ] SpatialFilterTest.SpatialFilterConfig_General (783 ms)
[ RUN      ] SpatialFilterTest.GetSpatialFilterParameters
[       OK ] SpatialFilterTest.GetSpatialFilterParameters (1780 ms)
[ RUN      ] SpatialFilterTest.GetSpatialFilterParameterLimits
[       OK ] SpatialFilterTest.GetSpatialFilterParameterLimits (2021 ms)
[ RUN      ] SpatialFilterTest.SpatialFilterConfig_JSON
[       OK ] SpatialFilterTest.SpatialFilterConfig_JSON (1858 ms)
[----------] 4 tests from SpatialFilterTest (6442 ms total)

[----------] 2 tests from General_Tests
[ RUN      ] General_Tests.Exceptions
[       OK ] General_Tests.Exceptions (0 ms)
[ RUN      ] General_Tests.Version
[       OK ] General_Tests.Version (0 ms)
[----------] 2 tests from General_Tests (0 ms total)

[----------] Global test environment tear-down
[==========] 43 tests from 6 test cases ran. (52571 ms total)
[  PASSED  ] 41 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] AppImagerTest.GetAppParameters
[  FAILED  ] AppImagerTest.GetImagerParameters

 2 FAILED TESTS
make[6]: *** [test/CMakeFiles/check] Error 1
make[5]: *** [test/CMakeFiles/check.dir/all] Error 2
make[4]: *** [test/CMakeFiles/check.dir/rule] Error 2
make[3]: *** [check] Error 2
make[2]: *** [O3D3XX_CAMERA-prefix/src/O3D3XX_CAMERA-stamp/O3D3XX_CAMERA-test] Error 2
make[1]: *** [CMakeFiles/O3D3XX_CAMERA.dir/all] Error 2
make: *** [all] Error 2

After running **o3d3xx-dump**, this is the output : 
namanpc@namanpc-All-Series:~/libo3d3xx/build/O3D3XX_CAMERA-prefix/src/O3D3XX_CAMERA-build/src/bin$ ./o3d3xx-dump
{
    "o3d3xx":
    {
        "libo3d3xx": "402",
        "Date": "Wed Apr 20 10:31:57 2016",
        "HWInfo":
        {
            "Mainboard": "#!02_M381_003_02178445_008022954",
            "Illumination": "#!02_I300_001_02118157_008001175",
            "MiraSerial": "0430-5384-0021-059c",
            "MACAddress": "00:02:01:40:2C:0C",
            "Frontend": "#!02_F342_002_15_00289_802259343",
            "Diagnose": "#!02_D322_C30_02157009_008023093",
            "Connector": "#!02_A300_001_02105252_008001175"
        },
        "SWVersion":
        {
            "IFM_Software": "1.3.1001",
            "Linux": "Linux version 3.11.0-00005-g2394d14 (eswadmin@dettlx79) (gcc version 4.7.2 (GCC) ) #1 SMP Wed Nov 25 16:10:41 CET 2015",
            "Diagnostic_Controller": "0.3.87",
            "ELDK": "GOLDENEYE_ELDK-2015-11-26_16-11-02-5321dac5357219d1408dbf7f53f164e8c138302a",
            "Calibration_Version": "0.9.0",
            "Calibration_Device": "00:02:01:40:2c:0c",
            "Main_Application": "0.4.100",
            "Algorithm_Version": "1.2.6"
        },
        "Device":
        {
            "Name": "New sensor",
            "Description": "",
            "ActiveApplication": "1",
            "PcicEipEnabled": "false",
            "PcicTcpPort": "50010",
            "PcicProtocolVersion": "3",
            "IOLogicType": "1",
            "IODebouncing": "true",
            "IOExternApplicationSwitch": "0",
            "SessionTimeout": "30",
            "ServiceReportPassedBuffer": "15",
            "ServiceReportFailedBuffer": "15",
            "ExtrinsicCalibTransX": "0",
            "ExtrinsicCalibTransY": "0",
            "ExtrinsicCalibTransZ": "0",
            "ExtrinsicCalibRotX": "0",
            "ExtrinsicCalibRotY": "0",
            "ExtrinsicCalibRotZ": "0",
            "EvaluationFinishedMinHoldTime": "10",
            "SaveRestoreStatsOnApplSwitch": "true",
            "IPAddressConfig": "0",
            "PasswordActivated": "false",
            "OperatingMode": "0",
            "DeviceType": "",
            "ArticleNumber": "",
            "ArticleStatus": "",
            "UpTime": "1.144125602437825e-316",
            "ImageTimestampReference": "23157600",
            "TemperatureFront1": "6.953222953505516e-310",
            "TemperatureFront2": "1.144149317588825e-316",
            "TemperatureIMX6": "1.144161175164325e-316",
            "TemperatureIllu": "6.953189366787785e-310"
        },
        "Net":
        {
            "MACAddress": "",
            "NetworkSpeed": "0",
            "StaticIPv4Address": "192.168.0.69",
            "StaticIPv4SubNetMask": "255.255.255.0",
            "StaticIPv4Gateway": "192.168.0.201",
            "UseDHCP": "false"
        },
        "Apps":
        [
            {
                "Name": "Sample Application",
                "Description": "",
                "TriggerMode": "1",
                "PcicTcpResultSchema": "{ \"layouter\": \"flexible\", \"format\": { \"dataencoding\": \"ascii\" }, \"elements\": [ { \"type\": \"string\", \"value\": \"star\", \"id\": \"start_string\" }, { \"type\": \"blob\", \"id\": \"normalized_amplitude_image\" }, { \"type\": \"blob\", \"id\": \"distance_image\" }, { \"type\": \"blob\", \"id\": \"x_image\" }, { \"type\": \"blob\", \"id\": \"y_image\" }, { \"type\": \"blob\", \"id\": \"z_image\" }, { \"type\": \"blob\", \"id\": \"confidence_image\" }, { \"type\": \"blob\", \"id\": \"diagnostic_data\" }, { \"type\": \"string\", \"value\": \"stop\", \"id\": \"end_string\" } ] }",
                "PcicEipResultSchema": "{ \"layouter\": \"flexible\", \"format\": { \"dataencoding\": \"binary\", \"order\": \"big\" }, \"elements\" : [ { \"type\": \"string\", \"value\": \"star\", \"id\": \"start_string\" }, { \"type\": \"records\", \"id\": \"models\", \"elements\": [ { \"type\": \"int16\", \"id\": \"boxFound\" }, { \"type\": \"int16\", \"id\": \"width\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"height\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"length\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"xMidTop\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"yMidTop\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"zMidTop\", \"format\": { \"scale\": 1000 } }, { \"type\": \"int16\", \"id\": \"yawAngle\" }, { \"type\": \"int16\", \"id\": \"qualityLength\" }, { \"type\": \"int16\", \"id\": \"qualityWidth\" }, { \"type\": \"int16\", \"id\": \"qualityHeight\" } ] }, { \"type\": \"string\", \"value\": \"stop\", \"id\": \"end_string\" } ] }",
                "LogicGraph": "{\"IOMap\": {\"OUT1\": \"RFT\",\"OUT2\": \"AQUFIN\"},\"blocks\": {\"B00001\": {\"pos\": {\"x\": 200,\"y\": 200},\"properties\": {},\"type\": \"PIN_EVENT_IMAGE_ACQUISITION_FINISHED\"},\"B00002\": {\"pos\": {\"x\": 200,\"y\": 75},\"properties\": {},\"type\": \"PIN_EVENT_READY_FOR_TRIGGER\"},\"B00003\": {\"pos\": {\"x\": 600,\"y\": 75},\"properties\": {\"pulse_duration\": 0},\"type\": \"DIGITAL_OUT1\"},\"B00005\": {\"pos\": {\"x\": 600,\"y\": 200},\"properties\": {\"pulse_duration\": 0},\"type\": \"DIGITAL_OUT2\"}},\"connectors\": {\"C00000\": {\"dst\": \"B00003\",\"dstEP\": 0,\"src\": \"B00002\",\"srcEP\": 0},\"C00001\": {\"dst\": \"B00005\",\"dstEP\": 0,\"src\": \"B00001\",\"srcEP\": 0}}}",
                "Type": "Camera",
                "Index": "1",
                "Id": "32358960",
                "Imager":
                {
                    "Channel": "0",
                    "ClippingBottom": "131",
                    "ClippingLeft": "0",
                    "ClippingRight": "175",
                    "ClippingTop": "0",
                    "ContinuousAutoExposure": "false",
                    "EnableAmplitudeCorrection": "true",
                    "EnableFastFrequency": "false",
                    "EnableFilterAmplitudeImage": "true",
                    "EnableFilterDistanceImage": "true",
                    "EnableRectificationAmplitudeImage": "false",
                    "EnableRectificationDistanceImage": "false",
                    "ExposureTime": "5000",
                    "ExposureTimeList": "125;5000",
                    "ExposureTimeRatio": "40",
                    "FrameRate": "5",
                    "MinimumAmplitude": "42",
                    "Resolution": "0",
                    "ClippingCuboid": "{\"XMin\": -3.402823e+38, \"XMax\": 3.402823e+38, \"YMin\": -3.402823e+38, \"YMax\": 3.402823e+38, \"ZMin\": -3.402823e+38, \"ZMax\": 3.402823e+38}",
                    "SpatialFilterType": "0",
                    "SymmetryThreshold": "0",
                    "TemporalFilterType": "0",
                    "ThreeFreqMax2FLineDistPercentage": "80",
                    "ThreeFreqMax3FLineDistPercentage": "80",
                    "TwoFreqMaxLineDistPercentage": "80",
                    "Type": "under5m_moderate",
                    "MaxAllowedLEDFrameRate": "0",
                    "SpatialFilter":
                    {
                        "Type": "0",
                        "TypeStr_": "Off"
                    },
                    "TemporalFilter":
                    {
                        "Type": "0",
                        "TypeStr_": "Off"
                    }
                }
            }
        ]
    }
}

I have already tried resetting the o3d3xx camera by running the command **o3d3xx-reset** but I still got the same output.
Also, libo3d3xx: version=0.4.2 and "IFM_Software": "1.3.1001".

Any help will be appreciated.
Thanks!

**Comment by tpanzarella** [comment]
You should update your camera to firmware version `1.4.1639`. On the main [README](https://github.com/lovepark/libo3d3xx/blob/master/README.md) we maintain a software compatibility matrix that maps compatible versions of `libo3d3xx` to the associated IFM firmware. The firmware is available in the `firmware` directory of this source distribution. The easiest way to do the update is to run `o3d3xx-reboot -r` from your build directory (since you don't have it installed yet). Then hit the sensor's internall http server at: `http://192.168.0.69:8080`. Here you can upload the firmware CPIO archive.

**Comment by NamanCMU** [comment]
Thanks tpanzarella! It worked :)
