### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by mikefoxnobel** [lovepark/libo3d3xx#61]
libo3d3xx/modules/camera/test/o3d3xx-camera-tests.cpp
Line 210,
`  EXPECT_EQ(std::stod(params.at("ExtrinsicCalibRotZ")),
            dev->ExtrinsicCalibRotY());`

It should be "ExtrinsicCalibRotY".

**Comment by tpanzarella** [comment]
Fixed on `master`. Thanks for the catch.
