### ISSUE TITLE
PNIODeviceName is not retained

### ISSUE THREAD

**Issue by tpanzarella** [lovepark/libo3d3xx#64]
@graugans  When setting the device config parameter `PNIODeviceName`, this value does not seem to be retained.  I am not getting an error when making the "setParameter" call over XML-RPC. However, it is always returning an empty string. I am seeing this while testing the new 1.6 firmware. JSON schema does not seem to indicate this as a read-only parameter.

**Comment by graugans** [comment]
PNIO stands for ProfiNet this is an industrial field bus. There is some weird logic to set the device name and it depends if the stack is running or not. In case of the camera it makes no sense to have the stack up and running. Especially for ProfiNet which is setting the network interface IP to ``0.0.0.0``
