### ISSUE TITLE
How to set 100k mode

### ISSUE THREAD

**Issue by jamesdebono** [lovepark/libo3d3xx#71]
Sorry if this is the wrong place to post such a question, I haven't found any user forum etc.
I am trying to set 100k mode per this: "We note that you really should use o3d3xx-dump and o3d3xx-config to create an application that employs the 100k imager"
I must be getting the syntax wrong, but can't find what is correct. I keep getting "XMLRPC value out of range" when I try changing resolution. What should I be setting it to? 
Update: I have seen in another post that I should be indeed setting it to 1, but this is yielding the error for me. I am using an o3d303 with lib 0.4.8 and fw1.6.2038

**Comment by graugans** [comment]
I am very sorry but 100k was removed from the regular O3D30x series.There will be a dedicated O3D3xx version with 100k support. Please contact your local ifm contact or maybe  @garrettplace can provide some details.

**Comment by jamesdebono** [comment]
Thanks I will discuss with the local IFM, but for now downgrading to firmware 1.4.1639 has worked
