### ISSUE TITLE
Error after upgrade firmware

### ISSUE THREAD

**Issue by zfxw0206** [lovepark/libo3d3xx#72]
After I upgrade the firmware to 1.6.2038, I got the following error:

****_terminate called after throwing an instance of 'o3d3xx::error_t'
  what():  XMLRPC device already has an edit session active
[o3d3xx70/camera-2] process has died [pid 7029, exit code -6, cmd /home/visiongm/wspace/devel/lib/o3d3xx/o3d3xx_node /cloud:=/o3d3xx70/camera/cloud /depth:=/o3d3xx70/camera/depth /depth_viz:=/o3d3xx70/camera/depth_viz /amplitude:=/o3d3xx70/camera/amplitude /raw_amplitude:=/o3d3xx70/camera/raw_amplitude /confidence:=/o3d3xx70/camera/confidence /good_bad_pixels:=/o3d3xx70/camera/good_bad_pixels /hist:=/o3d3xx70/camera/hist /xyz_image:=/o3d3xx70/camera/xyz_image /GetVersion:=/o3d3xx70/camera/GetVersion /Dump:=/o3d3xx70/camera/Dump /Config:=/o3d3xx70/camera/Config /Rm:=/o3d3xx70/camera/Rm __name:=camera __log:=/home/visiongm/.ros/log/1491db9c-a5cc-11e6-b6fd-003018c8f466/o3d3xx70-camera-2.log].
log file: /home/visiongm/.ros/log/1491db9c-a5cc-11e6-b6fd-003018c8f466/o3d3xx70-camera-2*.log_****

What does this mean? How can I fix it?

**Comment by tpanzarella** [comment]
You already have an active edit session with the camera (i.e., you are configuring its parameters over XML-RPC), and you are trying to create another one (edit session) without closing your previous one. Only one active edit session is allowed by the camera.

Now, how you got into that situation, I don't know. We don't have nearly enough info to help. Let's start with the version stack you are running: IFM Firmware, libo3d3xx, o3d3xx-ros

**Comment by zfxw0206** [comment]
After I got this error, I just wait for about 5 min, and run the camera.launch again, the error is gone. Thank you anyway.

**Comment by tpanzarella** [comment]
That is because the session with the camera timed out, and the camera cleaned it up for you.

You should still be sure you are running a supported software stack by looking at the README files for both `libo3d3xx` and `o3d3xx-ros`. On those pages, there is a compatibility matrix. I highly encourage you to make sure your stack is supported. Closing this for now.

**Comment by nathangeorge1** [comment]
I found this error pops up when running multiple thread (-j3) while trying to make the package as well. I'd suggest some kind of note in the quick start to not use -j3 when building.
