### ISSUE TITLE
Cross compilation for Raspberry Pi - pthread_create

### ISSUE THREAD

**Issue by dlaurent12** [lovepark/libo3d3xx#74]
The computer I use to cross compile is Debian stretch/sid.

The rootfs is based on the last raspbian (26-09-2016) based on Debian Jessie 8.

when I call cmake an error message appears linked to pthread_create. Probably the same with is describe in the article cross compile.

Please find attach the log files.

Best Regards

**Comment by graugans** [comment]
You may forgot to attach the logs?

**Comment by dlaurent12** [comment]
[logfile.zip](https://github.com/lovepark/libo3d3xx/files/589088/logfile.zip)

**Comment by dlaurent12** [comment]
Solved. Issue in toolchains.cmake file

**Comment by graugans** [comment]
@dlaurent12 I am glad to here you solved zour problem. Could you please be so kind and share your toolchain and maybe some details in form of a README? For example as a gist or in this issue. So others can use this as a starter.
